POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
  "password": "test001",
  "email": "test001@gmail.com",
  "username": "test001",
  "dob": "2002-08-01"
}

###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "password": "test001",
  "email": "test001@gmail.com"
}

###
GET http://localhost:8000/api/auth/test 